#!/bin/bash

# I use dotfiles in my home directory to ID the machine type i'm on.
if [ -f "/Users/grant/.symmetry" ]; then
  skainit='conda activate ska3; export PS1="ska3-$PS1"'
fi

if [ -f "/home/tremblay/.headlan" ]; then
  skainit='source /proj/sot/ska3/flight/bin/ska_envs.sh'
fi

# Initialize the ska environment. Screen will inherit it
$skainit

screen -S commbot -d -m python commbot.py --report_errors
echo "Starting commbot.py in a separate screen (use screen -r commbot) to attach to it" 
screen -S hrcsentinel -d -m python hrcsentinel.py --report_errors
echo "Starting hrcsentinel.py in a separate screen (use screen -r hrcsentinel) to attach to it"
